### ISSUE TITLE
code: 1006

### ISSUE THREAD

**Issue by LabelMinsk** [InnovateAsterisk/Browser-Phone#499]
Can you help me?

`phone.js:2136 
Failed to reconnect Error: WebSocket closed wss://192.168.39.90:8088/ws (code: 1006)
    at at.onWebSocketClose (sip-0.20.0.min.js:2:226066)
    at WebSocket.<anonymous> (sip-0.20.0.min.js:2:223454)`

**Comment by LabelMinsk** [comment]
Who meet that issue should know. You need turn on websocket in setting
